//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDEF_TopicosdeTI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int cli_codigo { get; set; }
        public string cli_nome { get; set; }
        public string cli_sobrenome { get; set; }
        public string cli_cidade { get; set; }
        public string cli_endereco { get; set; }
    }
}
